version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-2:262077174210:task-definition/ecs-prod:6"
        LoadBalancerInfo:
          ContainerName: "task-definition-prod"
          ContainerPort: 80
